/**
 * 业务数据总源 - 包含乐谱、教学视频、音频工程、课件教学、乐器电脑、AI电子、雪菲力及专栏文章
 */

export const CATEGORIES = [
  { id: 'all', name: '全部展品', icon: '⚡', color: 'var(--neo-yellow)', count: 0 },
  { id: 'sheet_music', name: '乐谱资源', icon: '🎼', color: 'var(--neo-pink)', count: 0 },
  { id: 'video_courses', name: '教学视频', icon: '🎬', color: 'var(--neo-purple)', count: 0 },
  { id: 'audio_engine', name: '音频工程', icon: '🎛️', color: 'var(--neo-cyan)', count: 0 },
  { id: 'teaching_ppt', name: '课件与教学', icon: '🎓', color: 'var(--neo-green)', count: 0 },
  { id: 'instruments_pc', name: '乐器与电脑', icon: '🎹', color: 'var(--neo-lime)', count: 0 },
  { id: 'ai_tech', name: 'AI与电子', icon: '🤖', color: 'var(--neo-blue)', count: 0 },
  { id: 'xuefeili_zone', name: '哈尔滨雪菲力', icon: '🥤', color: 'var(--neo-orange)', count: 0 },
  { id: 'freebies', name: '免费福利专区', icon: '🎁', color: 'var(--neo-green)', count: 0 },
  { id: 'articles', name: '专栏文章', icon: '📝', color: 'var(--neo-yellow)', count: 0 }
];

export const ITEMS_DATA = [
    // ----------------------------------------------------
  // 1. 乐谱资源 (真实曲库来自 D:\Adobe\琴谱，共 87 个高清文件)
  // ----------------------------------------------------
  {
    id: 'sheet-beethoven-08',
    category: 'sheet_music',
    title: "贝多芬《第八钢琴奏鸣曲“悲怆”》Op.13 全乐章 (亨乐权威原版)",
    desc: "德国亨乐原版 (G. Henle Verlag) 权威无差错定本：第一乐章庄板-辉煌的快板、第二乐章如歌的柔板、第三乐章回旋曲全集。",
    price: '¥ 10',
    priceValue: 10,
    tags: ["贝多芬", "亨乐原版", "悲怆奏鸣曲", "权威版本", "考级大曲"],
    badge: '亨乐权威',
    badgeColor: 'badge-blue',
    fileUrl: '/sheets/%E4%BA%A8%E4%B9%90%20%E8%B4%9D%E5%A4%9A%E8%8A%AC%20%E7%AC%AC%E5%85%AB%E9%A6%96%E7%AC%AC%E4%B8%80%E4%B9%90%E7%AB%A0.pdf',
    details: "包含亨乐原版权威无删节五线谱，带大师原版指法、分句呼吸与踏板建议。第一、二、三全乐章高清版。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-beethoven-14',
    category: 'sheet_music',
    title: "贝多芬《第十四钢琴奏鸣曲“月光”》Op.27 No.2 全曲 (亨乐原版)",
    desc: "亨乐权威定本：第一乐章持续的迟缓、第二乐章小快板、第三乐章激动的急板，古典主义向浪漫主义过渡最高巅峰。",
    price: '¥ 12',
    priceValue: 12,
    tags: ["贝多芬", "亨乐原版", "月光奏鸣曲", "考级十级", "世界名曲"],
    badge: '亨乐权威',
    badgeColor: 'badge-blue',
    fileUrl: '/sheets/%E4%BA%A8%E4%B9%90%20%E8%B4%9D%E5%A4%9A%E8%8A%AC%20%E7%AC%AC%E5%8D%81%E5%9B%9B%E9%A6%96.pdf',
    details: "4.6MB 高清矢量扫描版，第一乐章梦幻悠远，第三乐章极速琶音跑动，古典钢琴文献必修经典。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-beethoven-15',
    category: 'sheet_music',
    title: "贝多芬《第十五钢琴奏鸣曲“田园”》Op.28 全曲 (亨乐原版)",
    desc: "充满大自然恬静气息的田园奏鸣曲，7.6MB 亨乐原版大谱，低音持续音与歌唱性和声构思精妙。",
    price: '¥ 12',
    priceValue: 12,
    tags: ["贝多芬", "亨乐原版", "田园奏鸣曲", "经典名作"],
    badge: '亨乐原版',
    badgeColor: 'badge-blue',
    fileUrl: '/sheets/%E4%BA%A8%E4%B9%90%20%E8%B4%9D%E5%A4%9A%E8%8A%AC%20%E7%AC%AC%E5%8D%81%E4%BA%94%E9%A6%96.pdf',
    details: "包含第一乐章至第四乐章全套曲谱，亨乐排版清晰开阔，无残页涂抹，阅读视奏极其舒适。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-beethoven-05',
    category: 'sheet_music',
    title: "贝多芬《第五钢琴奏鸣曲》Op.10 No.1 第一乐章 (亨乐原版)",
    desc: "c小调极具戏剧冲击力与英雄色彩的快板乐章，附亨乐原版严谨指法与触键力度标记。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["贝多芬", "亨乐原版", "c小调", "考级选曲"],
    badge: '亨乐原版',
    badgeColor: 'badge-blue',
    fileUrl: '/sheets/%E8%B4%9D%E5%A4%9A%E8%8A%AC%E7%AC%AC%E4%BA%94%E9%A6%96%E7%AC%AC%E4%B8%80%E4%B9%90%E7%AB%A0%20%E4%BA%A8%E4%B9%90.pdf',
    details: "贝多芬早期充满活力的奏鸣曲精品，音符锐利饱满，适合中高级钢琴进阶者技术训练。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-wang-bainiao',
    category: 'sheet_music',
    title: "王建中《百鸟朝凤》原版钢琴独奏谱 (10页完整高清版)",
    desc: "根据同名唢呐曲改编的中国钢琴艺术巅峰名作！包含高难度华彩段落模仿百鸟啼鸣与热烈民间唢呐音色。",
    price: '¥ 12',
    priceValue: 12,
    tags: ["中国作品", "王建中", "百鸟朝凤", "音乐会大曲", "炫技经典"],
    badge: '中国经典',
    badgeColor: 'badge-orange',
    fileUrl: '/sheets/%E7%99%BE%E9%B8%9F%E6%9C%9D%E5%87%A4%20%20%20%E7%8E%8B%E5%BB%BA%E4%B8%AD%E7%99%BE%E9%B8%9F%E6%9C%9D%E5%87%A4%20%E5%8E%9F%E7%89%88%E9%92%A2%E7%90%B4%E8%B0%B1%20%2010%E9%A1%B5%20%20%E7%94%A8.pdf',
    details: "15.8MB 超清原版大谱，10页完整无删节，包含全部华彩、颤音与鸟鸣模拟技巧指法注释。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-wang-shandan',
    category: 'sheet_music',
    title: "王建中《山丹丹花开红艳艳》钢琴独奏原版高清谱",
    desc: "陕北民歌改编经典，抒情如歌的慢板引子与热烈欢腾的陕北大秧歌快板交替，考级与音乐会常演名曲。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["中国作品", "王建中", "考级必备", "陕北民歌"],
    badge: '考级经典',
    badgeColor: 'badge-orange',
    fileUrl: '/sheets/%E5%B1%B1%E4%B8%B9%E4%B8%B9%E8%8A%B1%E5%BC%80%E7%BA%A2%E8%89%B3%E8%89%B3%20%E7%8E%8B%E5%BB%BA%E4%B8%AD%20%E5%8E%9F%E7%89%88.pdf',
    details: "2.1MB 清晰原版五线谱，带准确指法与踏板标注，视奏流畅，练习重点清晰。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-wang-liuyanghe',
    category: 'sheet_music',
    title: "王建中《浏阳河》钢琴独奏原版高清谱",
    desc: "湖南民歌经典改编，流水般清澈动人的分解和弦与优美主旋律交相辉映，指法细腻考究。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["中国作品", "王建中", "浏阳河", "抒情名作"],
    badge: '名家改编',
    badgeColor: 'badge-orange',
    fileUrl: '/sheets/%E7%8E%8B%E5%BB%BA%E4%B8%AD%20%E6%B5%8F%E9%98%B3%E6%B2%B3.pdf',
    details: "双手琶音织体平衡训练绝佳教材，音质清亮，排版端正，适于音乐会表演与日常视奏。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-wang-collection',
    category: 'sheet_music',
    title: "《王建中钢琴作品选集》珍藏大曲谱全本汇编 (58MB)",
    desc: "58MB 超大高清扫描全本，汇集王建中先生一生经典钢琴改编曲与原创代表作完整合辑。",
    price: '¥ 25',
    priceValue: 25,
    tags: ["中国作品", "王建中", "全集大谱", "文献珍藏"],
    badge: '经典大谱',
    badgeColor: 'badge-yellow',
    fileUrl: '/sheets/%E7%8E%8B%E5%BB%BA%E4%B8%AD%E9%92%A2%E7%90%B4%E4%BD%9C%E5%93%81%E9%80%89.pdf',
    details: "收录《百鸟朝凤》《浏阳河》《山丹丹》《绣金匾》《彩云追月》等多首名曲完整总谱。",
    delivery: "本地超大原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-sun-chunwu',
    category: 'sheet_music',
    title: "孙以强《春舞》新疆风情钢琴独奏 (原版带指法)",
    desc: "浓郁的新疆手鼓节奏与冬不拉弹拨模拟，色彩绚丽奔放、技巧华丽闪烁的现代中国钢琴代表作。",
    price: '¥ 10',
    priceValue: 10,
    tags: ["中国作品", "孙以强", "春舞", "带指法", "新疆风格"],
    badge: '大师指法',
    badgeColor: 'badge-cyan',
    fileUrl: '/sheets/%E6%98%A5%E8%88%9E%20%E5%B8%A6%E6%8C%87%E6%B3%95%20%E5%8E%9F%E7%89%88.pdf',
    details: "2.9MB 高清原版谱，附详尽的连音与跳音触键指法指导，充分呈现西域天山脚下的春日欢歌。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-zhang-erxiao',
    category: 'sheet_music',
    title: "张朝《歌唱二小放牛郎叙事曲》大型中国钢琴独奏谱",
    desc: "著名作曲家张朝经典大型叙事曲，气势恢宏、戏剧性极强，专业比赛重量级选曲。",
    price: '¥ 12',
    priceValue: 12,
    tags: ["中国作品", "张朝", "大型叙事曲", "比赛曲目"],
    badge: '比赛大曲',
    badgeColor: 'badge-pink',
    fileUrl: '/sheets/%E5%BC%A0%E6%9C%9D%20%E5%8F%99%E4%BA%8B%E6%9B%B2%20%E6%AD%8C%E5%94%B1%E4%BA%8C%E5%B0%8F%E6%94%BE%E7%89%9B%E9%83%8E%E5%8F%99%E4%BA%8B%E6%9B%B2.pdf',
    details: "3.3MB 高清乐谱，将耳熟能详的童年旋律升华为史诗级交响化钢琴织体，震撼人心。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-zhang-numaamei',
    category: 'sheet_music',
    title: "张朝《努玛阿美》云南哈尼族风情钢琴曲",
    desc: "哈尼语“圣洁的光明之地”，充满原生态灵性律动与现代和声色彩的全国获奖佳作。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["中国作品", "张朝", "努玛阿美", "少数民族风情"],
    badge: '原生态灵韵',
    badgeColor: 'badge-lime',
    fileUrl: '/sheets/%E5%BC%A0%E6%9C%9D%E5%8A%AA%E7%8E%9B%E9%98%BF%E7%BE%8E.pdf',
    details: "独特的民间微分音律动与双手交替打击乐织体，现代中国钢琴教学前沿曲目。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-zhou-shanbei',
    category: 'sheet_music',
    title: "周广仁《陕北民歌主题变奏曲》原版高清谱",
    desc: "“中国钢琴教育灵魂”周广仁先生经典力作，主题取自陕北民歌，变奏构思精巧考究。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["中国作品", "周广仁", "变奏曲", "带指法"],
    badge: '泰斗经典',
    badgeColor: 'badge-yellow',
    fileUrl: '/sheets/%E6%B8%85%E6%99%B0%20%E5%91%A8%E5%B9%BF%E4%BB%81%20%E9%99%95%E5%8C%97%E6%B0%91%E6%AD%8C%E4%B8%BB%E9%A2%98%E5%8F%98%E5%A5%8F.pdf',
    details: "包含主题与各变奏完整排版，指法分配合理，是学习中国五声调式钢琴手法的必弹典范。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-chopin-op64no2',
    category: 'sheet_music',
    title: "肖邦《升c小调圆舞曲》Op.64 No.2 & Op.69 No.2",
    desc: "肖邦最脍炙人口的浪漫派圆舞曲，忧郁而华丽的波兰沙龙气质，附精细触键与指法标注。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["肖邦", "圆舞曲", "升c小调", "浪漫派经典"],
    badge: '浪漫典范',
    badgeColor: 'badge-pink',
    fileUrl: '/sheets/%E8%82%96%E9%82%A6op64no2%E7%89%88%E6%9C%AC.pdf',
    details: "肖邦作品核心曲目，旋律哀婉如歌，副歌快板如落英缤纷，附带准确指法与延音踏板提示。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-chopin-op40no1',
    category: 'sheet_music',
    title: "肖邦《A大调波兰舞曲“军队”》Op.40 No.1 高清版",
    desc: "极富英雄气概与爱国激情的军队波罗乃兹，辉煌的和弦跑动与刚劲的切分节奏。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["肖邦", "军队波兰舞曲", "辉煌大曲", "英雄气概"],
    badge: '英雄气概',
    badgeColor: 'badge-pink',
    fileUrl: '/sheets/%E8%82%96%E9%82%A6op40no1%E6%B8%85%E6%99%B0.pdf',
    details: "1.2MB 高清乐谱，和弦饱满、织体坚实，是锻炼手腕支撑与八度和弦爆发力的绝佳选曲。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-chopin-op25no9',
    category: 'sheet_music',
    title: "肖邦《蝴蝶练习曲》Op.25 No.9 降G大调正版乐谱",
    desc: "轻盈欢快的右手跳音与八度技巧，如蝴蝶翩翩起舞，考级与音乐会常演炫技短曲。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["肖邦", "蝴蝶练习曲", "技巧训练", "音乐会短曲"],
    badge: '技巧巅峰',
    badgeColor: 'badge-pink',
    fileUrl: '/sheets/%E8%82%96%E9%82%A6%20op25no9%20%E6%AD%A3%E7%89%88%20%20.pdf',
    details: "原版高清定本，仅两页纸却浓缩了高难度的手腕弹性跳音跑动技巧，练习效果立竿见影。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-liszt-hungary',
    category: 'sheet_music',
    title: "李斯特《匈牙利狂想曲精选》No.6/7/11/15拉科齐进行曲",
    desc: "李斯特极富吉普赛狂热的炫技代表作合辑，包含第6首著名双手八度、第15首拉科齐进行曲与第11首指法版。",
    price: '¥ 15',
    priceValue: 15,
    tags: ["李斯特", "匈牙利狂想曲", "拉科齐进行曲", "超级炫技"],
    badge: '炫技巅峰',
    badgeColor: 'badge-yellow',
    fileUrl: '/sheets/%E9%AB%98%E6%B8%85%20%E6%9D%8E%E6%96%AF%E7%89%B9%20%E5%8C%88%E7%89%99%E5%88%A9no15.pdf',
    details: "多套高清独立乐谱整合包，包含李斯特著名的匈牙利慢板（Lassan）与狂放快板（Friska）狂欢。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-liszt-s145',
    category: 'sheet_music',
    title: "李斯特《两首音乐会练习曲：侏儒之舞》S.145 原版谱",
    desc: "充满神秘童话色彩的极速半音阶与灵动跳音练习曲，钢琴专业高难度技巧试金石。",
    price: '¥ 10',
    priceValue: 10,
    tags: ["李斯特", "音乐会练习曲", "侏儒之舞", "大师炫技"],
    badge: '大师炫技',
    badgeColor: 'badge-yellow',
    fileUrl: '/sheets/%E6%9D%8E%E6%96%AF%E7%89%B9s145%E4%BE%8F%E5%84%92%20%E5%8E%9F%E7%89%88.pdf',
    details: "1.4MB 原版高清乐谱，细腻的音符对比与跳跃跑动，充分挖掘施坦威钢琴的音响潜能。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-mozart-k265',
    category: 'sheet_music',
    title: "莫扎特《小星星变奏曲》K.265 完整十二变奏 (带指法)",
    desc: "经典法兰西民歌主题变奏，纯真灵动的古典主义典范，带详尽练习指法与踏板指导。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["莫扎特", "小星星变奏曲", "带指法", "必弹经典"],
    badge: '必弹经典',
    badgeColor: 'badge-cyan',
    fileUrl: '/sheets/%E8%8E%AB%E6%89%8E%E7%89%B9k265%E5%B8%A6%E6%8C%87%E6%B3%95.pdf',
    details: "1.1MB 带指法精编谱，十二个变奏涵盖左手琶音、右手快速跑动、三连音、装饰音与对位技巧。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-mozart-k332',
    category: 'sheet_music',
    title: "莫扎特《F大调钢琴奏鸣曲》K.332 第一乐章 高清原版",
    desc: "歌唱性旋律与戏剧性转调的完美交融，考级八至九级核心经典大曲。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["莫扎特", "F大调奏鸣曲", "考级核心", "古典名篇"],
    badge: '古典名作',
    badgeColor: 'badge-cyan',
    fileUrl: '/sheets/%E9%AB%98%E6%B8%85%20%E8%8E%AB%E6%89%8E%E7%89%B9%20k332%20%E7%AC%AC%E4%B8%80%E4%B9%90%E7%AB%A0.pdf',
    details: "2.4MB 超清乐谱，包含了曼海姆乐派风格的小步舞曲动机与奔涌的断奏琶音。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-mozart-k545',
    category: 'sheet_music',
    title: "莫扎特《C大调钢琴奏鸣曲》K.545 第一乐章 快板原版",
    desc: "“易懂难精”的莫扎特标志性奏鸣曲，清亮透明的阿尔贝蒂低音与如歌琶音跑动。",
    price: '¥ 6',
    priceValue: 6,
    tags: ["莫扎特", "K545", "初学必弹", "经典教材"],
    badge: '入门必弹',
    badgeColor: 'badge-cyan',
    fileUrl: '/sheets/%E9%AB%98%E6%B8%85%20%E8%8E%AB%E6%89%8E%E7%89%B9%20k545%20%E7%AC%AC%E4%B8%80%E4%B9%90%E7%AB%A0%20%E5%8E%9F%E7%89%88.pdf',
    details: "古典钢琴学习者第一首真正意义上的规范奏鸣曲快板乐章，排版干净，无涂改。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-bach-sinfonia',
    category: 'sheet_music',
    title: "巴赫《二部创意曲》&《三部创意曲》选 (亨乐原版)",
    desc: "复调对位法基石教材，严谨的声部进出与主题摹仿，亨乐原版权威装饰音与分句解析。",
    price: '¥ 10',
    priceValue: 10,
    tags: ["巴赫", "亨乐原版", "复调进阶", "三部创意曲"],
    badge: '复调基石',
    badgeColor: 'badge-purple',
    fileUrl: '/sheets/%E5%B7%B4%E8%B5%AB%20%E4%BA%A8%E4%B9%90%20%E4%B8%89%E9%83%A8no4.pdf',
    details: "涵盖三部 No.4、二部 No.6 及 No.8，亨乐经典蓝皮版原版指法与断句指导。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-debussy-bergamasque',
    category: 'sheet_music',
    title: "德彪西《贝加莫组曲》四首全集 (含《月光》/带指法)",
    desc: "印象派钢琴世纪丰碑：含第一首《前奏曲》、第二首《小步舞曲》、第三首《月光》、第四首《巴斯皮耶》，附精炼法派指法。",
    price: '¥ 15',
    priceValue: 15,
    tags: ["德彪西", "月光", "印象派", "带指法全集"],
    badge: '印象派丰碑',
    badgeColor: 'badge-cyan',
    fileUrl: '/sheets/%E5%BE%B7%E5%BD%AA%E8%A5%BF%E8%B4%9D%E5%8A%A0%E8%8E%AB%E7%BB%84%E6%9B%B2%E5%85%A8%E9%9B%86%E5%B8%A6%E6%8C%87%E6%B3%95.pdf',
    details: "2.3MB 全套高清谱，尤其第三首《月光 (Clair de lune)》配有细致指法与朦胧印象派触键建议。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-debussy-arabesque',
    category: 'sheet_music',
    title: "德彪西《阿拉伯风格曲第一首》No.1 (精校带指法)",
    desc: "三连音流动如流水般优美绵密的早期代表作，充满柔美细腻的和声色彩与如歌线条。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["德彪西", "阿拉伯风格曲", "三连音", "带指法"],
    badge: '流光溢彩',
    badgeColor: 'badge-cyan',
    fileUrl: '/sheets/%E5%BE%B7%E5%BD%AA%E8%A5%BF2%E9%A6%96%E9%98%BF%E6%8B%89%E4%BC%AF%E9%A3%8E%E6%A0%BC%E6%9B%B2no1%E5%B8%A6%E6%8C%87%E6%B3%95.pdf',
    details: "二对三节奏与右手琶音交织的浪漫精品，指法精校，视奏顺畅。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-rach-op23no5',
    category: 'sheet_music',
    title: "拉赫玛尼诺夫《g小调前奏曲》Op.23 No.5 (大师指法版)",
    desc: "斯拉夫进行曲雄壮节奏与极度深情歌唱性中段，拉赫玛尼诺夫最知名代表作。",
    price: '¥ 10',
    priceValue: 10,
    tags: ["拉赫玛尼诺夫", "前奏曲", "进行曲", "大师指法"],
    badge: '宏伟辉煌',
    badgeColor: 'badge-pink',
    fileUrl: '/sheets/%E6%8B%89%E8%B5%AB%E7%8E%9B%E5%B0%BC%E8%AF%BA%E5%A4%AB%20op23no5%20%E6%8C%87%E6%B3%95%E7%89%88.pdf',
    details: "包含复杂密集的八度和弦推进与中段如天鹅绒般的抒情歌唱，大和弦指法分配精妙。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-schumann-op15',
    category: 'sheet_music',
    title: "舒曼《童年情景》Op.15 十三首全集 (含《梦幻曲》)",
    desc: "浪漫主义诗人写给成人的童话回忆录：含《异国和异国人民》《梦幻曲》《捉迷藏》等十三首完整高清乐谱。",
    price: '¥ 12',
    priceValue: 12,
    tags: ["舒曼", "梦幻曲", "童年情景", "浪漫主义全集"],
    badge: '浪漫诗篇',
    badgeColor: 'badge-pink',
    fileUrl: '/sheets/%E8%88%92%E6%9B%BC%E7%AB%A5%E5%B9%B4%E6%83%85%E6%99%AF%20op15%2013%E9%A6%96%E5%85%A8%E9%9B%86.pdf',
    details: "1.5MB 高清全本，舒曼灵动充满哲思与童趣的经典名作，旋律朴素纯真却意蕴悠长。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-tchaikovsky-seasons',
    category: 'sheet_music',
    title: "柴可夫斯基《四季》Op.37a：九月狩猎 / 十月秋之歌 / 十一月雪橇",
    desc: "俄罗斯浪漫抒情经典三部曲：深沉如诗的十月秋之歌、欢快奔驰的十一月雪橇车与威风凛凛的九月狩猎。",
    price: '¥ 12',
    priceValue: 12,
    tags: ["柴可夫斯基", "四季", "秋之歌", "俄罗斯浪漫派"],
    badge: '诗意经典',
    badgeColor: 'badge-green',
    fileUrl: '/sheets/%E6%9F%B4%E5%8F%AF%E5%A4%AB%E6%96%AF%E5%9F%BAop37ano10.pdf',
    details: "包含柴可夫斯基 Op.37a 核心最受喜爱的三个月季乐章，旋律催人泪下，纯正俄派气质。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-grieg-spring',
    category: 'sheet_music',
    title: "格里格 北欧风情选《致春天》&《侏儒进行曲》&《培尔金特朝景》",
    desc: "挪威民族乐派奠基人格里格代表三件套，融汇北欧峡湾春回大地的生机与挪威民间神怪传说奇趣。",
    price: '¥ 12',
    priceValue: 12,
    tags: ["格里格", "致春天", "北欧民族乐派", "抒情名曲"],
    badge: '北欧诗情',
    badgeColor: 'badge-green',
    fileUrl: '/sheets/%E6%A0%BC%E9%87%8C%E6%A0%BCop43no6%20%E8%87%B4%E6%98%A5%E5%A4%A9.pdf',
    details: "涵盖抒情小品 Op.43 No.6《致春天》、Op.54 No.3《侏儒进行曲》与 Op.46 No.4 钢琴独奏谱。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-mendelssohn-op14',
    category: 'sheet_music',
    title: "门德尔松《随想回旋曲》Op.14 (精校指法版)",
    desc: "优美柔和的行板引子与充满妖精般轻盈飞驰的快板回旋曲，门德尔松早期辉煌名作。",
    price: '¥ 10',
    priceValue: 10,
    tags: ["门德尔松", "随想回旋曲", "轻盈飞驰", "指法版"],
    badge: '音乐会名作',
    badgeColor: 'badge-purple',
    fileUrl: '/sheets/%E9%97%A8%E5%BE%B7%E5%B0%94%E6%9D%BEop14%E9%9A%8F%E6%83%B3%E5%9B%9E%E6%97%8B%E6%9B%B2%E6%8C%87%E6%B3%95%E7%89%88.pdf',
    details: "快速灵动的触键与高雅浪漫的沙龙气质，极适合手小而灵巧的演奏者登台炫技。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-sakamoto-lawrence',
    category: 'sheet_music',
    title: "坂本龙一《Merry Christmas Mr. Lawrence》原版独奏谱",
    desc: "教授最负盛名的传世经典，五声音阶东方禅意与西方现代和声结合的极致之作。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["坂本龙一", "劳伦斯", "经典原声", "治愈纯音"],
    badge: '传世经典',
    badgeColor: 'badge-cyan',
    fileUrl: '/sheets/%E5%8E%9F%E7%89%88%20%E5%9C%A3%E8%AF%9E%E5%BF%AB%E4%B9%90%20%E5%8A%B3%E4%BC%A6%E6%96%AF.pdf',
    details: "坂本龙一先生弹奏原版记谱，空灵而深沉的跨界和声，每个音符都敲击在灵魂深处。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-morricone-1900',
    category: 'sheet_music',
    title: "《海上钢琴师》插曲《Playing Love (爱之曲)》1900 原版独奏",
    desc: "1900 在舷窗边对心动女孩即兴弹奏的灵魂华彩，流转于黑白键间的纯粹爱情独白。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["海上钢琴师", "1900", "电影原声", "Playing Love"],
    badge: '影史留名',
    badgeColor: 'badge-pink',
    fileUrl: '/sheets/1_%E6%B5%B7%E4%B8%8A%E9%92%A2%E7%90%B4%E5%B8%88Playing%20love%201900.pdf',
    details: "埃尼奥·莫里康内经典配乐原谱，浪漫唯美的爵士变奏与深情叙事，电影原版记谱。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-maksim-croatian',
    category: 'sheet_music',
    title: "马克西姆《克罗地亚狂想曲》原版独奏谱 (附精校指法)",
    desc: "战火中的废墟狂想，热烈奔放的现代跨界钢琴神曲，附带右手八度跑动与节奏指法提示。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["马克西姆", "克罗地亚狂想曲", "热血跨界", "带指法"],
    badge: '热血神曲',
    badgeColor: 'badge-orange',
    fileUrl: '/sheets/%E5%85%8B%E7%BD%97%E5%9C%B0%E4%BA%9A%E7%8B%82%E6%83%B3%E6%9B%B2%20%E5%B8%A6%E6%8C%87%E6%B3%95.pdf',
    details: "动感强烈的十六分音符跳跃与切分低音，带详细参考指法，视奏即可上手弹奏。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-jay-hongchen',
    category: 'sheet_music',
    title: "周杰伦《红尘客栈》柔情中国风钢琴独奏谱",
    desc: "方文山作词、周杰伦作曲的经典中国风歌曲，柔美如流水般的钢琴改编独奏版。",
    price: '¥ 6',
    priceValue: 6,
    tags: ["周杰伦", "红尘客栈", "中国风", "流行钢琴"],
    badge: '周董经典',
    badgeColor: 'badge-pink',
    fileUrl: '/sheets/%E7%BA%A2%E5%B0%98%E5%AE%A2%E6%A0%88%20%E6%9F%94%E6%83%85%E7%89%88%20%E9%92%A2%E7%90%B4%E7%8B%AC%E5%A5%8F%281%29.pdf',
    details: "古筝韵律与流行钢琴织体的完美交织，易于上手，旋律动听优美。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-jay-woluolei',
    category: 'sheet_music',
    title: "周杰伦《我落泪·情绪零碎》特别转调激情版钢琴谱",
    desc: "充满情绪层层递进爆发力的高难度转调激情编配，流行钢琴玩家进阶必练。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["周杰伦", "我落泪情绪零碎", "转调版", "进阶独奏"],
    badge: '硬核编配',
    badgeColor: 'badge-pink',
    fileUrl: '/sheets/%E6%88%91%E8%90%BD%E6%B3%AA%E6%83%85%E7%BB%AA%E9%9B%B6%E7%A2%8E%EF%BC%88%E8%BD%AC%E8%B0%83passion%EF%BC%89.pdf',
    details: "特殊激情转调编配版，和弦密集饱满，低音八度推力极强，舞台演奏极富张力。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-jj-jiangnan',
    category: 'sheet_music',
    title: "林俊杰《江南》梦幻唯美钢琴改编独奏谱",
    desc: "圈圈圆圆圈圈的千古江南画卷，用现代钢琴清透和声重构的唯美梦幻改编。",
    price: '¥ 6',
    priceValue: 6,
    tags: ["林俊杰", "江南", "梦幻改编", "流行独奏"],
    badge: '流行金曲',
    badgeColor: 'badge-cyan',
    fileUrl: '/sheets/%E3%80%8A%E6%B1%9F%E5%8D%97%E3%80%8B%E6%A2%A6%E5%B9%BB%E7%89%88.pdf',
    details: "空灵梦幻的前奏引子与婉转如流水般的副歌铺陈，适合独奏与即兴配和弦练习。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-okawari-flowerdance',
    category: 'sheet_music',
    title: "DJ Okawari《Flower Dance (花之舞)》经典钢琴独奏原版",
    desc: "纯音界的封神天花板！清泉流响般的标志性右手琶音与感性旋律，原版高清五线谱。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["DJ Okawari", "花之舞", "Flower Dance", "治愈纯音"],
    badge: '纯音封神',
    badgeColor: 'badge-yellow',
    fileUrl: '/sheets/Dj%20okawari%20%E8%8A%B1%E4%B9%8B%E8%88%9E%20%E9%92%A2%E7%90%B4%E7%8B%AC%E5%A5%8F.pdf',
    details: "2.2MB 原版高清乐谱，精确记录花之舞标志性双手交错与流光溢彩的快速跑动。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-okawari-funk',
    category: 'sheet_music',
    title: "《花之舞》FUNK 律动爵士改编版 (独家附赠原版 MP3 伴奏音频!)",
    desc: "超炸裂的放克爵士风改编！包含完整独奏乐谱 PDF + 7.1MB 录音室级原版纯伴奏 MP3，插上音响即可震撼合奏！",
    price: '¥ 15',
    priceValue: 15,
    tags: ["花之舞", "FUNK爵士", "含MP3伴奏", "舞台合奏"],
    badge: '附赠音频伴奏',
    badgeColor: 'badge-orange',
    fileUrl: '/sheets/%E8%8A%B1%E4%B9%8B%E8%88%9E%20FUNK%E7%88%B5%E5%A3%AB%20%E9%92%A2%E7%90%B4%E7%8B%AC%E5%A5%8F.pdf',
    details: "包含《花之舞 FUNK爵士 钢琴独奏.pdf》乐谱与同名《花之舞 FUNK爵士 钢琴独奏 伴奏.mp3》音频全套资源。",
    delivery: "本地高清 PDF + 7.1MB MP3 伴奏原件 / 在线试读"
  },
  {
    id: 'sheet-kishibe-luvletter',
    category: 'sheet_music',
    title: "DJ Okawari / 岸部真明风格《Luv Letter (情书)》钢琴独奏",
    desc: "旋律如细雪飘落般浪漫深情的情书钢琴独奏版，治愈心灵的现代纯音乐名作。",
    price: '¥ 6',
    priceValue: 6,
    tags: ["Luv Letter", "情书", "治愈系", "浪漫纯音"],
    badge: '唯美治愈',
    badgeColor: 'badge-green',
    fileUrl: '/sheets/Luv%20Letter%20%E6%83%85%E4%B9%A6%E9%92%A2%E7%90%B4%E7%8B%AC%E5%A5%8F.pdf',
    details: "深情宁静，难度适中，适合初中级演奏者作为日常休闲练习或录制朋友圈视频曲目。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-yiruma-room',
    category: 'sheet_music',
    title: "李闰珉 (Yiruma)《Room with a View (看得见风景的房间)》独奏谱",
    desc: "韩国新世纪钢琴大师李闰珉温暖抒情名篇，窗外云淡风轻般的宁静叙事。",
    price: '¥ 6',
    priceValue: 6,
    tags: ["李闰珉", "Yiruma", "新世纪钢琴", "宁静唯美"],
    badge: '新世纪大师',
    badgeColor: 'badge-cyan',
    fileUrl: '/sheets/Room%20with%20a%20view%20%E6%9D%8E%E9%97%B0%E7%8F%89%20%E7%9C%8B%E5%BE%97%E8%A7%81%E9%A3%8E%E6%99%AF%E7%9A%84%E6%88%BF%E9%97%B4.pdf',
    details: "如涓涓细流般的抒情旋律，音调温暖明媚，适合在闲暇午后静心弹奏。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-dennis-track',
    category: 'sheet_music',
    title: "Dennis Kuo《Track in Time》唯美治愈钢琴独奏原版",
    desc: "时间轨迹里的温柔絮语，海外热门纯音乐博主经典曲目，全网高清原版。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["Dennis Kuo", "治愈钢琴", "海外原版", "高清PDF"],
    badge: '海外好评',
    badgeColor: 'badge-lime',
    fileUrl: '/sheets/track%20in%20time%E3%80%90%E7%8B%AC%E5%A5%8F%E3%80%91-%20dennis%20kuo%20-_967365.pdf',
    details: "3.7MB 超高分辨率五线谱，海外编配正版，触动心灵的平静旋律。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-mtaku-komorebi',
    category: 'sheet_music',
    title: "M-taku《Komorebi》穿过树梢的微光 钢琴独奏谱",
    desc: "日文“木漏れ日”的浪漫写照，清风拂过林间的跳跃光影，极具氛围感的日系独立纯音。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["M-taku", "Komorebi", "日系纯音", "高清独奏"],
    badge: '日系治愈',
    badgeColor: 'badge-lime',
    fileUrl: '/sheets/p2602%20Komorebi-M-taku-%E9%92%A2%E7%90%B4%E8%B0%B1.pdf',
    details: "2.9MB 精美五线谱，空灵动听的现代和声进行，富有治愈画面感。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-pianoboy-truth',
    category: 'sheet_music',
    title: "Pianoboy《你离开的真相》钢琴独奏 (含指法参考版)",
    desc: "华人流行纯音不朽经典，附带精细参考指法与踏板指导，新手必弹流行曲目。",
    price: '¥ 6',
    priceValue: 6,
    tags: ["Pianoboy", "你离开的真相", "流行钢琴", "带指法"],
    badge: '初学必弹',
    badgeColor: 'badge-pink',
    fileUrl: '/sheets/%E4%BD%A0%E7%A6%BB%E5%BC%80%E7%9A%84%E7%9C%9F%E7%9B%B8%20%E9%92%A2%E7%90%B4%E7%8B%AC%E5%A5%8F%282%29.pdf',
    details: "包含独奏谱以及参考指法版两份文件，循序渐进，新手友好。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-offenbach-cancan',
    category: 'sheet_music',
    title: "奥芬巴赫《康康舞曲 (Can Can)》双人四手联弹演奏大谱",
    desc: "雅克·奥芬巴赫《地狱中的奥菲欧》最欢腾热烈的经典名段，双人配合极具舞台感染力！",
    price: '¥ 10',
    priceValue: 10,
    tags: ["四手联弹", "康康舞曲", "双人合奏", "音乐会返场"],
    badge: '双人重奏',
    badgeColor: 'badge-purple',
    fileUrl: '/sheets/Can%20Can%20Piano%20Duet%20-%20Jacques%20Offenbach.pdf',
    details: "3.1MB 高清四手联弹大谱，Primo（高声部）与 Secondo（低声部）对照排版，合奏气氛绝佳。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-joplin-entertainer',
    category: 'sheet_music',
    title: "斯科特·乔普林《演艺人》四手联弹 (拉格泰姆雷格泰姆经典)",
    desc: "奥斯卡金奖电影《骗中骗》传世名曲，俏皮欢快的切分摇摆爵士节奏，四手联弹绝佳选段。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["四手联弹", "演艺人", "雷格泰姆", "爵士风情"],
    badge: '经典幽默',
    badgeColor: 'badge-purple',
    fileUrl: '/sheets/%E3%80%90S016%E3%80%91%E6%BC%94%E8%89%BA%E4%BA%BA%E5%9B%9B%E6%89%8B%E8%81%94%E5%BC%B9.pdf',
    details: "高低声部紧密交织的爵士切分节奏，教学展示与音乐会重奏的幽默返场首选。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-necke-post',
    category: 'sheet_music',
    title: "赫尔曼·奈克《邮递马车》四手联弹演奏级原版谱",
    desc: "生动逼真的马蹄声与快活喇叭声交织，韩国音乐出版社高标准精美排版，少年比赛保留曲。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["四手联弹", "邮递马车", "韩国版", "比赛热门"],
    badge: '重奏名作',
    badgeColor: 'badge-purple',
    fileUrl: '/sheets/%E9%82%AE%E9%80%92%E9%A9%AC%E8%BD%A6%20%E5%9B%9B%E6%89%8B%E8%81%94%E5%BC%B9%20%E9%9F%A9%E5%9B%BD%E7%89%88.pdf',
    details: "欢快跳跃，双人声部层次清晰，是各级少儿钢琴重奏比赛与汇报演出的经典曲目。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-stars-sigh',
    category: 'sheet_music',
    title: "《星星的叹息》钢琴五级比赛必备四手联弹曲谱 (22MB 高清原件)",
    desc: "国内考级与少儿钢琴比赛高频热选曲目，22MB 超清晰琴谱扫描原件，第一声部与第二声部对位详尽。",
    price: '¥ 10',
    priceValue: 10,
    tags: ["四手联弹", "考级五级", "星星的叹息", "比赛曲目"],
    badge: '考级五级',
    badgeColor: 'badge-purple',
    fileUrl: '/sheets/%E6%98%9F%E6%98%9F%E7%9A%84%E5%8F%B9%E6%81%AF%20%E4%BA%94%E7%BA%A7%20%E5%9B%9B%E6%89%8B%E8%81%94%E5%BC%B9%20%E6%AF%94%E8%B5%9B%E5%BF%85%E5%A4%87%E6%9B%B2%E7%9B%AE%281%29.pdf',
    details: "22MB 极高精度原件，细节毕现，声部对位极其规范，五级钢琴比赛推荐大谱。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-dianxing-pool',
    category: 'sheet_music',
    title: "池塘钢琴师《点星》钢琴独奏谱 (含 mapplezs 视频版 + 11.5MB 伴奏 MP3)",
    desc: "B站热门演奏家版本！包含视频演奏同款原谱 PDF + 11.5MB 高品质伴奏音频，一个人在家弹奏也能营造全乐队伴奏效果！",
    price: '¥ 15',
    priceValue: 15,
    tags: ["点星", "池塘钢琴师", "含伴奏MP3", "B站同款"],
    badge: '附全套伴奏',
    badgeColor: 'badge-orange',
    fileUrl: '/sheets/%E7%82%B9%E6%98%9Fmapplezs%E8%A7%86%E9%A2%91%E7%89%88.pdf',
    details: "包含《点星mapplezs视频版.pdf》乐谱与《点星伴奏for池塘钢琴师.mp3》11.5MB 纯伴奏原件。",
    delivery: "本地高清 PDF + 11.5MB MP3 伴奏原件 / 在线试读"
  },
  {
    id: 'sheet-galaxy-knight',
    category: 'sheet_music',
    title: "《银河骑士》热血现代跨界钢琴曲 (附赠带两拍起拍原版 MP3 伴奏!)",
    desc: "节奏感拉满的现代二次元热血钢琴名曲！独家附带带两拍提示起拍的高清原声伴奏音频 (8.2MB MP3)。",
    price: '¥ 15',
    priceValue: 15,
    tags: ["银河骑士", "热血纯音", "含起拍伴奏", "演出首选"],
    badge: '附起拍伴奏',
    badgeColor: 'badge-orange',
    fileUrl: '/sheets/%E9%93%B6%E6%B2%B3%E9%AA%91%E5%A3%AB.pdf',
    details: "包含 2.7MB 独奏总谱与 8.2MB 高音质纯伴奏音频（前带两拍节拍器起拍，跟伴奏绝不脱节）。",
    delivery: "本地高清 PDF + 8.2MB MP3 伴奏原件 / 在线试读"
  },
  {
    id: 'sheet-caldara-selve',
    category: 'sheet_music',
    title: "卡尔达拉《森林啊，充满希望 (Selve voi che le speranze)》钢琴伴奏谱",
    desc: "古典声乐意大利艺术歌曲经典必修曲目，bB 调声乐与钢琴伴奏双行总谱，高校声乐师生案头必备。",
    price: '¥ 8',
    priceValue: 8,
    tags: ["声乐艺术歌曲", "卡尔达拉", "钢琴伴奏", "意大利歌曲"],
    badge: '艺术歌曲伴奏',
    badgeColor: 'badge-blue',
    fileUrl: '/sheets/Selve%20voi%20che%20le%20speranze%20%E6%A3%AE%E6%9E%97%E5%95%8A%EF%BC%8C%E5%85%85%E6%BB%A1%E5%B8%8C%E6%9C%9B%28bB%29.pdf',
    details: "2.1MB 清晰版本，附意大利文原歌词对照，和声丰满平稳，声乐教学与钢琴艺术指导必备。",
    delivery: "本地原版高清 PDF / 支持在线即时试读"
  },
  {
    id: 'sheet-xinjiang-capriccio',
    category: 'sheet_music',
    title: "现代中国钢琴曲《新疆随想曲》全套乐谱珍藏手稿 (全套图片组)",
    desc: "多段变奏与浓烈西域调式，全套 11 张高清手稿与曲谱图片，生动展现新疆手鼓与踢踏舞律动。",
    price: '¥ 10',
    priceValue: 10,
    tags: ["中国作品", "新疆风情", "全套手稿", "高清图片"],
    badge: '珍稀手稿',
    badgeColor: 'badge-purple',
    fileUrl: '/sheets/%E6%96%B0%E7%96%86%E9%9A%8F%E6%83%B3%E6%9B%B2/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20260104155709_32_50.jpg',
    details: "全套 11 张高分辨率扫描原件，西域调式旋律与快速跑动打击乐律动相映成趣。",
    delivery: "本地全套高清图片组 / 支持在线即时试读"
  },

  // ----------------------------------------------------
  // 2. 教学视频 (Video Courses)
  // ----------------------------------------------------
  {
    id: 'video-01',
    category: 'video_courses',
    title: '抖音热门博主音乐与编曲教学视频合集',
    desc: '涵盖千万粉丝音乐博主独门声乐发声教学、流行钢琴即兴和弦套路、短视频爆款电音制作秘密。',
    price: '¥ 49 / 专题包',
    priceValue: 49,
    tags: ['抖音热门', '即兴伴奏', '短视频爆款', '通俗唱法'],
    badge: '爆款',
    badgeColor: 'badge-pink',
    details: '从呼吸咬字、高音闭合技巧，到流行和弦4536251进阶编排，博主通俗幽默的干货教学完整打包归档，无打码。',
    delivery: '云盘高清1080P/4K无水印视频'
  },
  {
    id: 'video-02',
    category: 'video_courses',
    title: '音乐学院名师公开课与专业大师班教学',
    desc: '中央音乐学院、上海音乐学院名师讲授视唱练耳进阶、钢琴触键法、古典声乐美声与民族发声技巧。',
    price: '¥ 68 / 课程',
    priceValue: 68,
    tags: ['名校大师班', '视唱练耳', '古典钢琴大师课', '声乐精研'],
    badge: '名师',
    badgeColor: 'badge-purple',
    details: '系统正统的学院派教学视频，每节课附带配套讲义与练耳练习音频，是考学进修及教师充电的最佳宝典。',
    delivery: '网盘分集打包归类'
  },
  {
    id: 'video-03',
    category: 'video_courses',
    title: '海外顶级音频博主教学视频 (中英双语整理)',
    desc: 'Dave Pensado、Warren Huart、Mix With The Masters等顶级制作人实战混音与母带处理课程。',
    price: '¥ 58 / 系列',
    priceValue: 58,
    tags: ['海外名师', 'MWTM母带', '格莱美制作人', '中英字幕'],
    badge: '进阶',
    badgeColor: 'badge-cyan',
    details: '解构欧美顶级流行音乐、嘻哈、摇滚分轨工程，学习模拟硬件运用、人声音色雕刻与空间混响深度融合秘技。',
    delivery: '网盘高清附中英双语字幕'
  },

  // ----------------------------------------------------
  // 3. 电子音乐工程与制作服务 (Audio Engineering)
  // ----------------------------------------------------
  {
    id: 'audio-01',
    category: 'audio_engine',
    title: '录音棚级人声精修 / Melodyne 音高节奏校准',
    desc: '纯手工精修音高与音准，修正颤音抖动与节奏脱拍，保留自然人声泛音与情感细节，告别电音机械感。',
    price: '¥ 80 起 / 轨',
    priceValue: 80,
    tags: ['Melodyne精修', '人声对齐', '保留呼吸质感', '消除跑调'],
    badge: '专业服务',
    badgeColor: 'badge-green',
    details: '采用 Melodyne Studio 深度多轨校音，逐字调整共鸣峰与微颤音。提供干湿对比试听，包修改至满意。',
    delivery: '提交干声后 24-48 小时交付 24bit/48kHz WAV 分轨'
  },
  {
    id: 'audio-02',
    category: 'audio_engine',
    title: '商业级贴唱 / 分轨混音与广播级母带处理',
    desc: 'EQ雕刻、动态多段压缩、人声瞬态塑形、立体声扩展、响度优化(达到流媒体 -14 LUFS 广播级响度标准)。',
    price: '¥ 200 起 / 首',
    priceValue: 200,
    tags: ['商业分轨混音', '模拟染色', '流媒体母带', '广播级标准'],
    badge: '硬核混音',
    badgeColor: 'badge-pink',
    details: '无论是一对一贴唱还是40轨全乐队工程，结合高端母带链条，打造通透、温暖、具备穿透力的商业流行作品。',
    delivery: '提供无损 WAV + 320k MP3 + 伴奏无声版伴奏带'
  },
  {
    id: 'audio-03',
    category: 'audio_engine',
    title: '电脑机架声卡远程部署 / 代安装调试',
    desc: 'Studio One / Cubase / Samplitude 机架电音效果搭建，专业跳线调试、麦克风降噪与直播连麦防卡音。',
    price: '¥ 120 / 次',
    priceValue: 120,
    tags: ['机架部署', '声卡跳线', '直播特效', '远程一键搞定'],
    badge: '好评',
    badgeColor: 'badge-cyan',
    details: '支持各类 USB/雷电专业声卡（福克斯特、雅马哈、罗兰、RME、艾肯等），远程协助调音，定制专属人声音色。',
    delivery: '向日葵/ToDesk 远程一对一包调好'
  },
  {
    id: 'audio-04',
    category: 'audio_engine',
    title: '主流混音插件包 / 机架宿主软件代安装配置',
    desc: 'FabFilter 肥波全套、Waves Horizon、Soundtoys 效果器、iZotope Ozone 母带全套及宿主环境快速配置。',
    price: '¥ 50 起',
    priceValue: 50,
    tags: ['插件全家桶', 'FabFilter肥波', 'Waves母带', '即装即用'],
    badge: '工具',
    badgeColor: 'badge-yellow',
    details: '整理纯净稳定免冲突的音频插件安装包与详细部署向导，支持 Windows / macOS 系统，含预设库。',
    delivery: '云盘下载 + 图文/远程安装指导'
  },
  {
    id: 'audio-05',
    category: 'audio_engine',
    title: '高端软音源编制 / 编曲配器与伴奏扒带定制',
    desc: 'Kontakt 顶级管弦乐(Spitfire/Cinematic)、真实钢琴与吉他音源编制，承接原创歌曲编曲与高质量伴奏制作。',
    price: '¥ 500 起 / 首',
    priceValue: 500,
    tags: ['专业编曲', '软音源制作', '管弦乐编制', '无损还原伴奏'],
    badge: '高阶定制',
    badgeColor: 'badge-purple',
    details: '多年编曲实战经验，熟练运用各厂商管弦、民族、电子合成器音色，按照客户需求定制旋律与风格编排。',
    delivery: '交付全分轨音频 + MIDI 伴奏工程'
  },
  {
    id: 'audio-06',
    category: 'audio_engine',
    title: 'AI 深度人声伴奏无损分离 / 专业乐谱扒制',
    desc: '提取原曲纯伴奏、无损提取干声人声，将任意音频转制为标准五线谱、简谱或吉他六线谱（含工程MIDI）。',
    price: '¥ 30 起 / 首',
    priceValue: 30,
    tags: ['伴奏分离', '人声提取', '扒谱制谱', '出高清PDF/MIDI'],
    badge: '快工',
    badgeColor: 'badge-green',
    details: '采用业内顶级深度学习音频分轨算法，消除串音，保留鼓组与低频弹性；手工校验五线谱与节奏小节线。',
    delivery: '当天交付分离无损音频 / Sibelius导出高清乐谱'
  },

  // ----------------------------------------------------
  // 4. 教学、课件与学术服务 (Teaching & Academic)
  // ----------------------------------------------------
  {
    id: 'teach-01',
    category: 'teaching_ppt',
    title: '教师公开课 / 赛课课件制作与高级美化',
    desc: '针对中小学及高校教师赛课、评优公开课量身定制 PPT，排版大气，动效流畅，契合教学目标重难点。',
    price: '¥ 80 起 / 份',
    priceValue: 80,
    tags: ['赛课获奖PPT', '动态交互', '教学设计深度融合', '定制美化'],
    badge: '优质服务',
    badgeColor: 'badge-yellow',
    details: '不仅是外观美化，更懂得教学设计逻辑。搭配生动板书设计、随堂测验互动页面与沉浸式多媒体嵌入。',
    delivery: '提供 PPTX 源文件 + 演讲备注'
  },
  {
    id: 'teach-02',
    category: 'teaching_ppt',
    title: '精品微课视频剪辑制作与片头特效包装',
    desc: '包含绿幕抠像、画中画合成、专业字幕、MG关键帧动画、背景音乐声效搭配，让微课脱颖而出。',
    price: '¥ 150 起 / 条',
    priceValue: 150,
    tags: ['微课剪辑', '绿幕抠像', '字幕动效', '省级获奖标准'],
    badge: '精品',
    badgeColor: 'badge-pink',
    details: '全套 Premiere + After Effects 制作，保障视频 1080P 高清输出，音画完美同步，符合官方报送格式标准。',
    delivery: '交付 MP4 高清成片与工程归档'
  },
  {
    id: 'teach-03',
    category: 'teaching_ppt',
    title: '学术讲座高端 PPT 设计 & 专家发言稿润色',
    desc: '学术研讨会、行业论坛主题汇报 PPT，数据图表化呈现，搭配结构严谨、逻辑缜密的大会发言讲稿撰写。',
    price: '¥ 120 起',
    priceValue: 120,
    tags: ['学术报告', '高端路演', '发言稿定制', '逻辑缜密'],
    badge: '商务学术',
    badgeColor: 'badge-cyan',
    details: '深谙学术汇报与演说节奏，将冗长文字精炼为清晰的信息图表，发言稿标注重音、停顿与演讲时长规划。',
    delivery: '交付标准 PPTX 与 Word 讲稿'
  },
  {
    id: 'teach-04',
    category: 'teaching_ppt',
    title: '流行与古典钢琴一对一精品教学 (线上/哈尔滨线下)',
    desc: '流行钢琴和弦速成、即兴伴奏实战法则、古典钢琴考级拔高。因材施教，趣味性与专业度兼备。',
    price: '¥ 150 / 课时',
    priceValue: 150,
    tags: ['钢琴教学', '即兴和弦速成', '考级辅导', '一对一实战'],
    badge: '资深教师',
    badgeColor: 'badge-green',
    details: '突破枯燥练习曲，从听辨旋律、和弦色彩到双手自由即兴，快速掌握弹唱与独奏精髓，哈尔滨同城可面授。',
    delivery: '线上腾讯会议多机位直播 / 哈尔滨线下琴房'
  },
  {
    id: 'teach-05',
    category: 'teaching_ppt',
    title: '音乐学与音乐教育学术论文辅导 / 开题文献梳理',
    desc: '知网/万方音乐类核心文献深度检索、论文选题可行性分析、开题报告逻辑架构指导、学术规范查重辅导。',
    price: '¥ 300 起',
    priceValue: 300,
    tags: ['开题研讨', '文献梳理', '音乐学论文辅导', '学术规范格式'],
    badge: '学术顾问',
    badgeColor: 'badge-purple',
    details: '聚焦音乐表演、音乐史学、现代音乐教育学等专业方向，协助理清研究框架、撰写开题报告提纲及格式规范。',
    delivery: '语音一对一研讨 + 框架思路批注文档'
  },

  // ----------------------------------------------------
  // 5. 乐器与电脑硬件零售 (Instruments & PC)
  // ----------------------------------------------------
  {
    id: 'inst-01',
    category: 'instruments_pc',
    title: '名优品牌古筝精选零售 (初学入门至演奏级)',
    desc: '扬州名厂原木整板古筝、红木螺钿/刻字工艺，音色清亮纯正，发货前专业调音师亲自定弦与试音。',
    price: '¥ 1280 起 / 架',
    priceValue: 1280,
    tags: ['品牌古筝', '扬州名厂', '送全套配件', '包邮到家'],
    badge: '热销乐器',
    badgeColor: 'badge-pink',
    details: '随琴赠送高档加厚琴包、实木琴架、防过敏玳瑁指甲、专用调音器与防尘罩，哈尔滨本地支持送货上门。',
    delivery: '德邦/顺丰特快保价直达，本地可上门自提试琴'
  },
  {
    id: 'inst-02',
    category: 'instruments_pc',
    title: '品牌原装钢琴 & 精选进口二手琴 (雅马哈/卡瓦依)',
    desc: '严格甄选日本原产雅马哈(U1/U3)、卡瓦依(BL/US)二手精选琴，机械状态九成新，无虫蛀潮湿。',
    price: '¥ 9800 起 / 台',
    priceValue: 9800,
    tags: ['进口钢琴', '雅马哈U系列', '原装音板', '质保5年'],
    badge: '品质保证',
    badgeColor: 'badge-yellow',
    details: '全琴经过资深钢琴调律师全套整音、整调、调律，键感灵敏，音色饱满深沉，提供5年核心部件质保。',
    delivery: '专业钢琴搬运团队配送，哈尔滨本地免费调律一次'
  },
  {
    id: 'inst-03',
    category: 'instruments_pc',
    title: '专业音乐制作 / 游戏剪辑电脑主机定制组装',
    desc: '针对编曲宿主(低DPC延迟、大内存跑音源)、视频渲染及高画质游戏定制装机，硬件透明，拒绝矿卡杂牌。',
    price: '¥ 3800 起 / 台',
    priceValue: 3800,
    tags: ['定制装机', '超静音水冷', '编曲专用优化', '三年质保'],
    badge: '极客装机',
    badgeColor: 'badge-cyan',
    details: '精选一线大厂 CPU、高频低时序大内存（32G/64G/128G）、高速 PCIe 4.0 SSD，风道经过超静音优化，录音不进杂音。',
    delivery: '顺丰防震保价发货 / 哈尔滨本地送货上门'
  },
  {
    id: 'inst-04',
    category: 'instruments_pc',
    title: '专业音频系统深度调试 / Windows 精简调优',
    desc: '解决专业声卡爆音、掉驱动、高音频延迟问题，精简系统后台冗余服务，定制专业级低延迟音频工作流。',
    price: '¥ 80 / 次',
    priceValue: 80,
    tags: ['低DPC延迟', '彻底告别爆音', '精简服务', '稳定如磐石'],
    badge: '硬核排障',
    badgeColor: 'badge-lime',
    details: '通过 LatencyMon 深度诊断系统驱动瓶颈，优化电源计划、CPU 核心调度与注册表，专为录音编曲环境打造。',
    delivery: '远程一对一优化，测试合格后交付'
  },

  // ----------------------------------------------------
  // 6. AI与电子前沿技术 (Tech & AI)
  // ----------------------------------------------------
  {
    id: 'ai-01',
    category: 'ai_tech',
    title: 'AI 辅助编程开发 / 自动化脚本定制',
    desc: '基于 Python / JS 开发各类自动化办公脚本、批量音频重命名、数据采集与自动化工具，降本增效。',
    price: '¥ 100 起 / 项',
    priceValue: 100,
    tags: ['AI编程', 'Python脚本', '自动化工具', '效率飞升'],
    badge: '极客生产力',
    badgeColor: 'badge-blue',
    details: '结合现代大模型编写高可读性、鲁棒的代码，交付即可运行的打包可执行程序或脚本文件，附详细说明。',
    delivery: '交付源码与完整使用教程'
  },
  {
    id: 'ai-02',
    category: 'ai_tech',
    title: '主流 AI 工具实战运用指导 (ChatGPT/Claude/Suno/MJ)',
    desc: '从提示词工程到商业落地：用 Suno 一键生成高品质商业歌曲雏形，用 Midjourney 设计专辑封面，用 Claude 辅助写作。',
    price: '¥ 120 / 小时',
    priceValue: 120,
    tags: ['Suno编曲', 'Midjourney设计', '提示词工程', '实战答疑'],
    badge: '前沿热点',
    badgeColor: 'badge-purple',
    details: '不讲空洞理论，只讲实操手把手技巧。快速掌握当前最强大 AI 工具链在音乐制作、内容生成与设计中的全流程应用。',
    delivery: '线上语音屏幕共享实操教学'
  },
  {
    id: 'ai-03',
    category: 'ai_tech',
    title: '稀缺专业软件资源代找 / 环境兼容部署',
    desc: '各行业小众冷门生产力工具、古董系统专用软件、专业工程软件部署与版本兼容性疑难杂症解决。',
    price: '¥ 40 起',
    priceValue: 40,
    tags: ['软件代找', '环境部署', '疑难排查', '效率至上'],
    badge: '极客寻宝',
    badgeColor: 'badge-yellow',
    details: '凭借多年技术沉淀与海内外资源库检索渠道，帮你快速找到稳定可用的专业生产力工具，解决安装报错。',
    delivery: '云盘资源直发 + 安装运行指引'
  },

  // ----------------------------------------------------
  // 7. 哈尔滨雪菲力一级经销专区 (Xuefeili)
  // ----------------------------------------------------
  {
    id: 'xuefeili-01',
    category: 'xuefeili_zone',
    title: '哈尔滨雪菲力汽水经典荔枝味 (整箱24瓶/听)',
    desc: '老哈尔滨人的白月光！清爽气泡搭配浓郁荔枝果香，冷藏后口感绝佳，聚餐、烧烤、火锅必备神仙饮品。',
    price: '¥ 48 / 箱 (批发特惠)',
    priceValue: 48,
    tags: ['哈尔滨特产', '雪菲力荔枝味', '原厂正品', '冰镇绝配'],
    badge: '哈尔滨老铁认准',
    badgeColor: 'badge-orange',
    details: '官方一级正规渠道供货，日期新鲜，保质期充裕。支持单箱自提、多箱同城配送，量大更优惠。',
    delivery: '哈尔滨市区支持自提/货拉拉冷链配送，外地走物流'
  },
  {
    id: 'xuefeili-02',
    category: 'xuefeili_zone',
    title: '雪菲力经典甜橙味 / 复合果味汽水整箱',
    desc: '经典老味甜橙汽水，气足沙口，酸甜爽口解油腻，红白喜事、开业庆典、烧烤店批量进货首选。',
    price: '¥ 48 / 箱',
    priceValue: 48,
    tags: ['经典甜橙', '餐饮店供货', '婚庆宴会批发', '气足沙口'],
    badge: '一级经销',
    badgeColor: 'badge-orange',
    details: '稳定货源保障，长期为哈尔滨各大烧烤店、东北铁锅炖、连锁餐饮店稳定供应雪菲力系列汽水。',
    delivery: '哈尔滨本地固定路线定期送货上门'
  },
  {
    id: 'xuefeili-03',
    category: 'xuefeili_zone',
    title: '雪菲力汽水餐饮批发 & 聚会团购合作方案',
    desc: '面向哈尔滨同城餐饮门店、校园超市、企业团建、大型活动的一站式批发供货，价格美丽，货源稳定。',
    price: '整车/大宗批发面议',
    priceValue: 0,
    tags: ['大宗批发', '餐饮合作', '长期供货', '送货上门'],
    badge: '批发特供',
    badgeColor: 'badge-yellow',
    details: '雪菲力一级代理商直供，免去中间层层加价。签订长期供货协议享月结与品牌促销海报支持。',
    delivery: '直接电话/微信对接经理快速订货'
  },

  // ----------------------------------------------------
  // 8. 免费福利专区 (Freebies)
  // ----------------------------------------------------
  {
    id: 'free-01',
    category: 'freebies',
    title: '【免费领】2026 流行钢琴精选原版高清谱包 (20首)',
    desc: '包含周杰伦、毛不易、告五人、Taylor Swift 等中外热门金曲简易五线谱合集，零门槛免费领取！',
    price: '¥ 0.00 (免费)',
    priceValue: 0,
    tags: ['免费乐谱', '高清PDF', '精挑细选', '一键转存'],
    badge: '100% FREE',
    badgeColor: 'badge-green',
    details: '站长个人整理的入门到进阶流行钢琴曲谱集，排版清晰无杂乱水印，适合打印弹奏或平板阅谱。',
    delivery: '点击详情直接获取百度网盘/夸克提取码'
  },
  {
    id: 'free-02',
    category: 'freebies',
    title: '【免费领】混音常用脉冲响应 (IR) 混响卷积预设包',
    desc: '包含 Lexicon 480L、Bricasti M7、著名大教堂实景采样的顶级 IR 脉冲文件，宿主通用！',
    price: '¥ 0.00 (免费)',
    priceValue: 0,
    tags: ['混音神器', '免费IR预设', '人声空间感', '通用WAV格式'],
    badge: '福利',
    badgeColor: 'badge-lime',
    details: '适用于各类卷积混响插件（如 REVerence, Waves IR1, FL Convolver 等），让人声瞬间置身于千万元级声学空间。',
    delivery: '直接下载压缩包，内附使用视频说明'
  },
  {
    id: 'free-03',
    category: 'freebies',
    title: '【免费领】Windows 音频降延迟一键优化批处理脚本',
    desc: '站长亲手编写的 Windows 注册表与电源计划优化脚本，一键释放 CPU 核心，抑制爆音与毛刺感。',
    price: '¥ 0.00 (免费)',
    priceValue: 0,
    tags: ['开源脚本', '一键调优', '低延迟音频', '极客免费分享'],
    badge: '站长力荐',
    badgeColor: 'badge-cyan',
    details: '开源透明的 bat 脚本，不植入任何推广软件，安全无害，适合音频创作者与游戏玩家提升系统实时响应。',
    delivery: '点击详情复制脚本或直接下载'
  },

  // ----------------------------------------------------
  // 9. 专栏文章 (Articles)
  // ----------------------------------------------------
  {
    id: 'art-01',
    category: 'articles',
    title: '《从零打造低延迟无爆音录音混音宿主环境实战避坑手册》',
    desc: '许多音乐人经常被声卡爆音、ASIO 冲突、跳线无声所折磨。本文从 Windows 底层音频调度机制详解如何一劳永逸搞定专业机架环境。',
    price: '干货专栏',
    priceValue: 0,
    tags: ['音频科普', '宿主调优', 'ASIO避坑', '干货实录'],
    badge: '置顶好文',
    badgeColor: 'badge-yellow',
    date: '2026-03-10',
    content: `
      <p><strong>前言：</strong>玩音乐工程最令人头疼的不是灵感枯竭，而是按下播放键时那一声刺耳的“咔哒”爆音与系统无响应。很多朋友换了上万元的专业声卡，依然摆脱不了 DPC Latency 飘红的噩梦。</p>
      <p><strong>第一步：抓住系统元凶——DPC 延迟</strong><br>绝大多数 Windows 系统爆音的罪魁祸首并不是 CPU 算力不足，而是显卡驱动、Wi-Fi 节能管理或者电源省电状态在强行打断实时音频流。下载 LatencyMon，测试 10 分钟，就能抓出占用中断时间最长的驱动文件。</p>
      <p><strong>第二步：锁定高性能电源与核心停用</strong><br>在系统电源选项中开启“卓越性能”模式，并彻底禁用 USB 选择性挂起，防止声卡供电突降导致掉驱动。在 BIOS 中关闭 C-States 省电技术，确保音频渲染时 CPU 主频稳定如山。</p>
      <p><strong>第三步：合理的 Buffer Size（缓冲大小）设置</strong><br>录音与修音阶段，将 Buffer Size 设为 64 或 128 samples 保证近乎零延迟；而在混音母带挂载大量母带级插件时，果断提高到 512 或 1024 samples，给宿主充足的运算缓冲，享受丝滑创作！</p>
    `
  },
  {
    id: 'art-02',
    category: 'articles',
    title: '《AI Suno 与编曲工具兴起：独立音乐制作人该拥抱还是抵触？》',
    desc: '深度解析现代大模型在音频生成的现状，从旋律结构、音色调校到人情味的不可替代性，探讨独立创作者的破局之道。',
    price: '思考杂谈',
    priceValue: 0,
    tags: ['AI音乐', 'Suno实测', '音乐人出路', '生产力进化'],
    badge: '深度解析',
    badgeColor: 'badge-purple',
    date: '2026-02-28',
    content: `
      <p>从 Suno 到各类 AI 编曲插件，现代 AI 已经在几十秒内能生成一首五脏俱全的流行伴奏。许多同行感叹“音乐制作的门槛消失了”。但真正深入商业落地的音乐人知道，AI 目前最大的痛点在于<strong>不可控的微观细节与情感颗粒度</strong>。</p>
      <p>商业客户往往需要的是“主歌第16小节鼓点留白半拍，接一个温暖的长混响大提琴独奏”。对于这种极度精确且动态的变化，目前的黑盒大模型是无能为力的。真正聪明的做法，是将 AI 当作<strong>灵感碰撞发生器</strong>与<strong>快速草稿机</strong>，而后续的精细修音、真乐器录制、声场塑形与商业母带，依然是专业工程师的绝对壁垒。</p>
    `
  },
  {
    id: 'art-03',
    category: 'articles',
    title: '《老哈尔滨人的舌尖白月光：雪菲力荔枝味汽水的气泡情怀》',
    desc: '在哈尔滨的大街小巷，吃着铁签子小烧烤、喝着冰镇雪菲力，是这座冰雪之城最接地气的人间烟火。',
    price: '本地随笔',
    priceValue: 0,
    tags: ['哈尔滨情怀', '雪菲力故事', '人间烟火', '美食地图'],
    badge: '哈尔滨记忆',
    badgeColor: 'badge-orange',
    date: '2026-01-15',
    content: `
      <p>外地朋友常问我：“哈尔滨除了哈啤和大白梨，还有什么本地人割舍不掉的饮料？”答案毫无疑问是<strong>雪菲力（Xuefeili）</strong>。</p>
      <p>尤其是那一抹经典的荔枝味，绿底瓶标，开盖瞬间那股窜鼻的气泡声，伴随着清冽甘甜的果香，简直是夏日吃烤冷面和冬天下馆子吃铁锅炖的绝杀搭档。作为哈尔滨本地的一级经销商，我每天看着一箱箱雪菲力送到各大餐饮老店，深深感到这不仅仅是一瓶饮料，更是哈尔滨人的集体味蕾记忆。无论走到哪里，一口冰镇雪菲力，就是回家的滋味！</p>
    `
  }
];
